engvocab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("vocapp.urls"), name="vocapp"),
    path("admin/", admin.site.urls),
]

vocapp/urls.py
from django.urls import path

from . import views

app_name = "vocapp"
urlpatterns = [
	path("", views.redir_home, name="redir_home"),
	path("home", views.home, name="home"),
	path("search", views.search, name="search"),
	path("expression/<int:expression_id>", views.inspect_expression, name="inspect_expression"),
	path("about", views.about, name="about"),
	path("progress", views.progress, name="progress"),
    path("profile", views.profile, name="profile"),
	path("login", views.login_user, name="login_user"),
	path("signup", views.signup, name="signup"),
	path("logout", views.logout_user, name="logout_user"),
	path("adjust_confidence/<int:expression_id>", views.adjust_confidence, name="adjust_confidence"),
	path("update_filters", views.update_filters, name="update_filters"),
	path("report/<int:expression_id>", views.report, name="report"),
]

vocapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import MaxLengthValidator


class Role(models.Model):
	role = models.CharField(max_length=30, primary_key=True)

	def __str__(self):
		return self.role


class Level(models.Model):
	level = models.CharField(max_length=10, primary_key=True)

	def __str__(self):
		return self.level


class Expression(models.Model):
	content = models.CharField(max_length=75, null=False, blank=False, unique=True)
	translation_it = models.CharField(max_length=100, null=True)
	note = models.CharField(max_length=350, null=True)
	context = models.CharField(max_length=100, null=True)
	example_en = models.CharField(max_length=200, null=True)
	example_it = models.CharField(max_length=200, null=True)
	is_phrasal_verb = models.BooleanField(default=False)
	is_formal = models.BooleanField(default=False)
	is_figurative = models.BooleanField(default=False)
	role = models.ForeignKey(Role, on_delete=models.CASCADE)
	level = models.ForeignKey(Level, on_delete=models.CASCADE)

	def __str__(self):
		return self.content


class User(AbstractUser):
	expression = models.ManyToManyField(Expression, through='Learn')


class Learn(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	expression = models.ForeignKey(Expression, on_delete=models.CASCADE)
	confidence = models.IntegerField(default=0)


class Report(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	expression = models.ForeignKey(Expression, on_delete=models.CASCADE)
	fields = models.CharField(max_length=100, null=False, blank=False)
	message = models.TextField(max_length=350, blank=True, validators=[MaxLengthValidator(350)])
	created_at = models.DateTimeField(auto_now_add=True)

vocapp/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class SignupForm(UserCreationForm):
	def __init__(self, *args, **kargs):
		super().__init__(*args, **kargs)
		self.fields["username"].widget.attrs.update({
			'require': '',
			'name' : 'username',
			'minlength' : '3',
			'maxlength' : '150',
			'autofocus' : '',
			'id':'id_username',
			'placeholder' : 'Username',
		})
		self.fields["password1"].widget.attrs.update({
			'require': '',
			'name' : 'password1',
			'id':'id_password1',
			'placeholder' : 'Password',
		})
		self.fields["password2"].widget.attrs.update({
			'require': '',
			'name' : 'password2',
			'id':'id_password2',
			'placeholder' : 'Retype password',
		})
	class Meta:
		model = get_user_model()
		fields = ['username', 'password1', 'password2']	#field to be included in the form

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)
	def __init__(self, *args, **kargs):
		super().__init__(*args, **kargs)
		self.fields["username"].widget.attrs.update({
			'require': '',
			'name' : 'username',
			'minlength' : '3',
			'maxlength' : '150',
			'autofocus' : '',
			'id':'id_username',
			'placeholder' : 'Username',
		})
		self.fields["password"].widget.attrs.update({
			'require': '',
			'name' : 'password',
			'id':'id_password',
			'placeholder' : 'Password',
		})

vocapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout 
from django.urls import reverse
from django.utils.html import escape
from .forms import LoginForm, SignupForm

from .models import *
from .custom_exceptions import EmptyQuery
from random import choice

import json
import re


CONFIDENCE_BAR = 420
CONFIDENCE_PARAMETERS = {
	"A1/A2": 140,
	"B1" : 84,
	"B1+" : 60,
	"B2" : 42,
	"C1/C2" : 35
}
FORCED_EXPRESSION_ID = None
VALID_REPORT_FIELDS = {'content', 'transl', 'note', 'context', 'expl', 'expl_it', 'phrasal', 'formal', 'figurative', 'role', 'lvl'}


def redir_home(request):
	return redirect('vocapp:home')


def adjust_confidence(request, expression_id):
	if request.user.is_authenticated:
		user = User.objects.get(username=request.user.username)
		expr = Expression.objects.get(pk = expression_id)
		try:
			association = Learn.objects.get(user = user, expression = expr)
			if (request.POST["guessing"] == '1'):	# guessed
				association.confidence += CONFIDENCE_PARAMETERS[str(expr.level)]
			association.save()
		except Learn.DoesNotExist:	# create a new association between user and expression
			if (request.POST["guessing"] == '1'):	# guessed
				new_association = Learn(user = user, expression = expr, confidence=CONFIDENCE_PARAMETERS[str(expr.level)])
			else:
				new_association = Learn(user = user, expression = expr, confidence=0)
			new_association.save()
		return HttpResponseRedirect(reverse("vocapp:home"))

	# if there is no user logged in just redirect to home
	return redirect('vocapp:home')


def update_filters(request):
	request.session["level_filters"] = []
	request.session["phrasal"] = False
	request.session["category"] = "discover"
	if ("level" in request.GET):
		for level in dict(request.GET)["level"]:
			if level in CONFIDENCE_PARAMETERS.keys():
				request.session["level_filters"].append(level)

	if ("phrasal" in request.GET):
		request.session["phrasal"] = True

	if ("category" in request.GET):
		if request.GET["category"] == "review":
			request.session["category"] = request.GET["category"]

	return HttpResponseRedirect(reverse("vocapp:home"))


def filter_expressions(levels, phrasal, category, user):
	expressions_set = None

	# DISCOVER or REVIEW
	if category == "review" and user.is_authenticated:
		expressions_set = Expression.objects.filter(learn__user_id = user.id, learn__confidence__gte = 0)
		if not expressions_set:
			raise EmptyQuery(1)
	elif category == "discover" and user.is_authenticated:
		discovered_ids = Learn.objects.filter(user_id = user.id).values_list('expression_id', flat=True)
		expressions_set = Expression.objects.exclude(id__in=discovered_ids)
		if not expressions_set:
			raise EmptyQuery(2)
	else:
		expressions_set = Expression.objects.all()
		if not expressions_set:
			raise EmptyQuery(3)

	# LEVEL FILTERS and PHRASAL VERB
	if (levels == []):
		if (phrasal):
			filtered_ids = expressions_set.filter(is_phrasal_verb = True).values_list('id', flat = True)
			if not filtered_ids:
				raise EmptyQuery(4)
		else:
			filtered_ids = expressions_set.values_list('id', flat = True)
			if not filtered_ids:
				raise EmptyQuery(5)
	else:
		if (phrasal):
			filtered_ids = expressions_set.filter(is_phrasal_verb = True, level__in=levels).values_list('id', flat=True)
			if not filtered_ids:
				raise EmptyQuery(6)
		else:
			filtered_ids = expressions_set.filter(level__in=levels).values_list('id', flat=True)
			if not filtered_ids:
				raise EmptyQuery(7)
			
	if not filtered_ids:
		raise EmptyQuery(0)
	
	return expressions_set.get(pk = choice(filtered_ids))


def get_other_translations(expression):
	match = re.search(r'\((\d+)\)', expression.content)
	if match:	# if the expression contains "(<number>)"
		number = match.group(1) # extract the number
		word = expression.content.split(f' ({number})')[0]  # get the word before the number
		return Expression.objects.filter(content__icontains=f'{word} (').exclude(id=expression.id) # get the other translations of the same word
	else:
		return []


def home(request):
	global FORCED_EXPRESSION_ID
	levels = Level.objects.values_list('level', flat = True)

	if FORCED_EXPRESSION_ID:
		context = {
			"levels": levels,
			"expression_info": Expression.objects.get(pk = FORCED_EXPRESSION_ID),
			"other_translations": get_other_translations(Expression.objects.get(pk = FORCED_EXPRESSION_ID)),
			"error" : {}
		}
		FORCED_EXPRESSION_ID = None
		return render(request, "vocapp/home.html", context)

	if ("level_filters" not in request.session.keys()):
		request.session["level_filters"] = []
	
	if ("phrasal" not in request.session.keys()):
		request.session["phrasal"] = False
	
	if ("category" not in request.session.keys()):
		request.session["category"] = "discover"

	try:
		expression_data = filter_expressions(request.session["level_filters"], request.session["phrasal"], request.session["category"], request.user)
	except EmptyQuery as e:
		context = {
			"levels": levels,
			"expression_info": {},
			"other_translations": [],
			"error": e,
		}
	else:
		context = {
			"levels": levels,
			"expression_info": expression_data,
			"other_translations": get_other_translations(expression_data),
			"error" : {}
		}
	return render(request, "vocapp/home.html", context)


def search(request):
	expressions_list = dict(Expression.objects.values_list('id', 'content'))
	context = {
		"expressions_list" : json.dumps(expressions_list),
	}
	return render(request, "vocapp/search.html", context)


def inspect_expression(request, expression_id):
	global FORCED_EXPRESSION_ID
	expression_info = Expression.objects.get(pk = expression_id)
	if FORCED_EXPRESSION_ID:
		FORCED_EXPRESSION_ID = None
	context = {
		"expression_id" : expression_id,
		"expression_info": expression_info,
		"other_translations": get_other_translations(expression_info),
	}
	return render(request, "vocapp/expression.html", context)


# check if the redirect_url is from expression page or home page
def validate_redirect(request, redirect_url):
	home_url = request.build_absolute_uri(reverse("vocapp:home"))
	expression_url = request.build_absolute_uri(reverse("vocapp:inspect_expression", kwargs={"expression_id": 0}))
	expression_url = expression_url.replace("/0", "/")

	if redirect_url == home_url or redirect_url.startswith(expression_url):
		return True
	else:
		return False


def report(request, expression_id):
	global FORCED_EXPRESSION_ID
	global VALID_REPORT_FIELDS
	if not validate_redirect(request, request.META.get('HTTP_REFERER', '/')):
		return redirect("vocapp:home")
	if request.user.is_authenticated:
		if request.method == "POST":
			if "message" not in request.POST or "involved_fields" not in request.POST:
				FORCED_EXPRESSION_ID = expression_id
				return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
			fields_string = ""
			for field in request.POST.getlist("involved_fields"):
				if field in VALID_REPORT_FIELDS:
					fields_string += field + "-"
			expression = Expression.objects.get(pk = expression_id)
			message = escape(request.POST["message"])
			report = Report(user = request.user, expression = expression, fields = fields_string, message = message)
			report.save()
			FORCED_EXPRESSION_ID = expression_id
	return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def progress(request):
	# check if user is autenticated, if not redirect to home
	if request.user.is_authenticated:
		discovered_ids = Learn.objects.filter(user_id = request.user.id).values_list('expression_id', flat=True)
		never_seen = Expression.objects.exclude(id__in=discovered_ids).count()
		learning = Learn.objects.filter(user=request.user.id, confidence__range=(0, CONFIDENCE_BAR-1)).count()
		learned = Learn.objects.filter(user=request.user.id, confidence__gte=CONFIDENCE_BAR).count()
		expressions_by_level = Expression.objects.values('level').annotate(total=models.Count('level'))
		learning_expressions_by_level = Learn.objects.filter(user=request.user.id, confidence__lt=CONFIDENCE_BAR).values('expression__level').annotate(total=models.Count('expression__level'))
		learned_expressions_by_level = Learn.objects.filter(user=request.user.id, confidence__gte=CONFIDENCE_BAR).values('expression__level').annotate(total=models.Count('expression__level'))
		never_seen_expressions_by_level = Expression.objects.exclude(id__in=discovered_ids).values('level').annotate(total=models.Count('level'))

		never_seen_expressions_by_level = {item['level']: item['total'] for item in never_seen_expressions_by_level}
		expressions_by_level = {item['level']: item['total'] for item in expressions_by_level}
		learning_expressions_by_level = {item['expression__level']: item['total'] for item in learning_expressions_by_level}
		learned_expressions_by_level = {item['expression__level']: item['total'] for item in learned_expressions_by_level}
		levels = Level.objects.values_list('level', flat = True)
		levels = {level: (never_seen_expressions_by_level.get(level, 0), learning_expressions_by_level.get(level, 0), learned_expressions_by_level.get(level, 0), expressions_by_level[level]) for level in levels}


		never_seen_expression_list = Expression.objects.exclude(id__in=discovered_ids).order_by('content')
		learning_expression_list = Expression.objects.filter(learn__user=request.user.id, learn__confidence__lt=CONFIDENCE_BAR).order_by('content')
		learned_expression_list = Expression.objects.filter(learn__user=request.user.id, learn__confidence__gte=CONFIDENCE_BAR).order_by('content')
		context = {
			"never_seen" : never_seen,
			"learning" : learning,
			"learned" : learned,
			"total_expressions": never_seen + learning + learned,
			"levels": levels,
			"never_seen_expression_list": never_seen_expression_list,
			"learning_expression_list": learning_expression_list,
			"learned_expression_list": learned_expression_list,
		}
		return render(request, "vocapp/progress.html", context)
	else:
		return redirect("vocapp:login_user")

vocapp/templates/vocapp/expression.html
{% extends "layout_template.html" %}

{% block main %}
{% load static %}
<main class="flex_container_col_hcent">

	<div class="flex_container_col_hcent top-bottom-spacing">
		<div id="table_container" class="flex_container_col_cent">
			<table>
				<tbody>
					<tr>
						<th>Level</th>
						<th>Role</th>
						<th>Context</th>
						{% if expression_info.is_phrasal_verb %}
						<th>Other info 1</th>
						{% endif %}
						{% if expression_info.is_formal %}
						<th>Other info 2</th>
						{%endif%}
						{% if expression_info.is_figurative %}
						<th>Other info 3</th>
						{%endif%}
					</tr>
					<tr>
						<td>{{expression_info.level}}</td>
						<td>{{expression_info.role}}</td>
						<td>{{expression_info.context}}</td>
						{% if expression_info.is_phrasal_verb %}
							<td>phrasal verb</td>
						{% endif %}
						{% if expression_info.is_formal %}
							<td>formal</td>
						{%endif%}
						{% if expression_info.is_figurative %}
							<td>figurative</td>
						{%endif%}
					</tr>
				</tbody>
			</table>
		</div>
		
		<p class="content">{{expression_info.content}}</p>
		<p class="translation">{{expression_info.translation_it}}</p>

		<div id="translation_info_container">
			{% if other_translations %}
				<p id="other_translations">Other translations:</p>
				<ul id="other_translations_list">
					{% for translation in other_translations %}
						<li>{{translation.content}}: {{translation.translation_it}}</li>
					{% endfor %}
				</ul>
			{% endif %}
			<p id="example_en"><strong>Example</strong>: {{expression_info.example_en}}</p>
			<p id="example_it"><strong>Esempio</strong>: {{expression_info.example_it}}</p>
			<p id="notes"><strong>Note</strong>: {{expression_info.note}}</p>
		</div>
		{% if request.user.is_authenticated %}
			<div>
				<button id="report_button" onclick = "toggle_report_form()">Report error <img src="{% static 'vocapp/icons/arrow_down.svg' %}" alt=""></button>
			</div>
			<div class="report_form hidden_object">
				<form class="flex_container_col_hcent" action="{%url 'vocapp:report' expression_info.id%}" method="POST" onsubmit="check_report_form(event)">
					{% csrf_token %}
					<p>Which fields contain errors?</p>
					<div class="fields_list flex_container_col_start">
						<div>
							<input type="checkbox" name="involved_fields" value="content" id="content_error">
							<label for="content_error">Expression</label>
						</div>
						
						<div>
							<input type="checkbox" name="involved_fields" value="transl" id="translation_error">
							<label for="translation_error">Translation</label>
						</div>
						
						<div>
							<input type="checkbox" name="involved_fields" value="lvl" id="level_error">
							<label for="level_error">Level</label>
						</div>

						<div>
							<input type="checkbox" name="involved_fields" value="role" id="role_error">
							<label for="role_error">Role</label>
						</div>
						
						<div>
							<input type="checkbox" name="involved_fields" value="context" id="context_error">
							<label for="context_error">Context</label>
						</div>

						<div>
							<input type="checkbox" name="involved_fields" value="expl" id="example_error">
							<label for="example_error">Example</label>
						</div>

						<div>
							<input type="checkbox" name="involved_fields" value="expl_it" id="example_it_error">
							<label for="example_it_error">Example translation</label>
						</div>

						<div>
							<input type="checkbox" name="involved_fields" value="note" id="note_error">
							<label for="note_error">Note</label>
						</div>
						
						<div>
							<input type="checkbox" name="involved_fields" value="phrasal" id="phrasal_error">
							<label for="phrasal_error">"Phrasal verb" tag</label>
						</div>

						<div>
							<input type="checkbox" name="involved_fields" value="formal" id="formal_error">
							<label for="formal_error">"Formal" tag</label>
						</div>
						
						<div>
							<input type="checkbox" name="involved_fields" value="figurative" id="figurative_error">
							<label for="figurative_error">"Figurative" tag</label>
						</div>
					</div>

					<textarea name="message" id="error_message" cols="40" rows="15" required placeholder="Describe the error"></textarea>
					<button id="submit_report_button" type="submit">Send</button>
				</form>
			</div>
		{% endif %}
	</div>
</main>
<script src="{% static 'vocapp/js/typing_sim.js' %}"></script>
<script src="{% static 'vocapp/js/report.js' %}"></script>
<script>
	"{% if request.user.is_authenticated %}"
		add_report_events();
	"{% endif %}"
</script>
{% endblock %}

vocapp/templates/vocapp/home.html
{% extends "layout_template.html" %}

{% block main %}
{% load static %}
<main class="flex_container_col_hcent">
	<form class="flex_container_col_hcent" action="{%url 'vocapp:update_filters'%}" method="GET">
		<div id="filters">
			<div class="flex_container_row_cent" id="levels">
				{% for level in levels %}
					<div class="filter">
						<input type="checkbox" name="level" id="{{level}}" class="filter_checkbox" value="{{level}}" {%if level in request.session.level_filters%} checked {%endif%}>
						<label for="{{level}}" {%if level in request.session.level_filters %} class="filter_on" {% endif %}>{{level}}</label>
					</div>
				{%endfor%}
			</div>
			<div class="flex_container_row_cent" id="other">
				<div class="filter">
					<input type="checkbox" name="phrasal" id="phrasal" class="filter_checkbox" value="phrasal" {%if request.session.phrasal %} checked class="filter_on" {% endif %}>
					<label for="phrasal" {%if request.session.phrasal %} class="filter_on" {% endif %}>phrasal verb</label>
				</div>
				{% if request.user.is_authenticated %}
					<div class="filter">
						<input type="checkbox" name="category" id="review" class="filter_checkbox" value="review" {%if request.session.category == 'review'%} checked {%endif%}>
						<label for="review" {%if request.session.category == 'review' %} class="filter_on" {% endif %}>review</label>
					</div>
				{% endif %}
			</div>
		</div>
		<button type="submit" id="apply_filter_button">Apply filters</button>
	</form>
	<hr>
	<div id ="guessing_section" class="flex_container_col_hcent">
		{%if expression_info %}
			<div id="table_container" class="flex_container_row_cent">
				<table>
					<tbody>
						<tr>
							<th>Level</th>
							<th>Role</th>
							<th>Context</th>
							{% if expression_info.is_phrasal_verb %}
							<th>Other info 1</th>
							{% endif %}
							{% if expression_info.is_formal %}
							<th>Other info 2</th>
							{%endif%}
							{% if expression_info.is_figurative %}
							<th>Other info 3</th>
							{%endif%}
						</tr>
						<tr>
							<td>{{expression_info.level}}</td>
							<td>{{expression_info.role}}</td>
							<td>{{expression_info.context}}</td>
							{% if expression_info.is_phrasal_verb %}
								<td>phrasal verb</td>
							{% endif %}
							{% if expression_info.is_formal %}
								<td>formal</td>
							{%endif%}
							{% if expression_info.is_figurative %}
								<td>figurative</td>
							{%endif%}
						</tr>
					</tbody>
				</table>
			</div>
			<p id="expression_slot" class="content"></p>

			<button id="show_button" class="visible_object" onclick="show_solution()">Show</button>
			
			<div id="solution" class="hidden_object flex_container_col_hcent" >
				<p class="translation translation-color">{{expression_info.translation_it}}</p>

				<div id="translation_info_container">
					{% if other_translations %}
						<p id="other_translations">Other translations:</p>
						<ul id="other_translations_list">
							{% for translation in other_translations %}
								<li>{{translation.content}}: <span class="translation-color">{{translation.translation_it}}</span></li>
							{% endfor %}
						</ul>
					{% endif %}
					<p id="example_en"><strong>Example</strong>: {{expression_info.example_en}}</p>
					<p id="example_it"><strong>Esempio</strong>: {{expression_info.example_it}}</p>
					<p id="notes"><strong>Note</strong>: {{expression_info.note}}</p>
				</div>
				<div id="guess_buttons" class="flex_container_row_cent">
					<form action="{%url 'vocapp:adjust_confidence' expression_info.id%}" method="POST">
						{% csrf_token %}
						<button type ="submit" class = "guess_button" name="guessing" value="0">Not guessed</button>
					</form>
					<form action="{%url 'vocapp:adjust_confidence' expression_info.id%}" method="POST">
						{% csrf_token %}
						<button type ="submit" class = "guess_button" name="guessing" value="1">Guessed</button> 
					</form>
				</div>

				{% if request.user.is_authenticated %}
					<div>
						<button id="report_button" onclick = "toggle_report_form()">Report error <img src="{% static 'vocapp/icons/arrow_down.svg' %}" alt=""></button>
					</div>
					<div class="report_form hidden_object">
						<form class="flex_container_col_hcent" action="{%url 'vocapp:report' expression_info.id%}" method="POST" onsubmit="check_report_form(event)">
							{% csrf_token %}
							<p>Which fields contain errors?</p>
							<div class="fields_list flex_container_col_start">
								<div>
									<input type="checkbox" name="involved_fields" value="content" id="content_error">
									<label for="content_error">Expression</label>
								</div>
								
								<div>
									<input type="checkbox" name="involved_fields" value="transl" id="translation_error">
									<label for="translation_error">Translation</label>
								</div>
								
								<div>
									<input type="checkbox" name="involved_fields" value="lvl" id="level_error">
									<label for="level_error">Level</label>
								</div>

								<div>
									<input type="checkbox" name="involved_fields" value="role" id="role_error">
									<label for="role_error">Role</label>
								</div>
								
								<div>
									<input type="checkbox" name="involved_fields" value="context" id="context_error">
									<label for="context_error">Context</label>
								</div>

								<div>
									<input type="checkbox" name="involved_fields" value="expl" id="example_error">
									<label for="example_error">Example</label>
								</div>

								<div>
									<input type="checkbox" name="involved_fields" value="expl_it" id="example_it_error">
									<label for="example_it_error">Example translation</label>
								</div>

								<div>
									<input type="checkbox" name="involved_fields" value="note" id="note_error">
									<label for="note_error">Note</label>
								</div>
								
								<div>
									<input type="checkbox" name="involved_fields" value="phrasal" id="phrasal_error">
									<label for="phrasal_error">"Phrasal verb" tag</label>
								</div>

								<div>
									<input type="checkbox" name="involved_fields" value="formal" id="formal_error">
									<label for="formal_error">"Formal" tag</label>
								</div>
								
								<div>
									<input type="checkbox" name="involved_fields" value="figurative" id="figurative_error">
									<label for="figurative_error">"Figurative" tag</label>
								</div>
							</div>

							<textarea name="message" id="error_message" cols="40" rows="15" required placeholder="Describe the error"></textarea>
							<button id="submit_report_button" type="submit">Send</button>
						</form>
					</div>
				{% endif %}
			</div>
		{% else %}
			<p>{{error}}</p>
		{% endif %}
	</div>
</main>

<script defer>
	//initialize the filter_command using the session variable
	window.filter_command = ""
	"{% if request.session.level_filters%}"
		window.filter_command = "filter";
	
		"{%for level in request.session.level_filters %}"
			window.filter_command += " " + "{{level}}";
		"{%endfor%}"
	"{% endif %}"

	"{%if request.session.phrasal %}"
		if (window.filter_command == "") {
			window.filter_command = "filter";
		}
		window.filter_command += " " + "phrasal";
	"{% endif %}"

	"{%if request.session.category == 'review'%}"
		if (window.filter_command == "") {
			window.filter_command = "filter";
		}
		window.filter_command += " " + "review";
	"{%endif%}"
</script>

<script src="{% static 'vocapp/js/home.js' %}"></script>
<script src="{% static 'vocapp/js/report.js' %}"></script>
<script src="{% static 'vocapp/js/typing_sim.js' %}"></script>

<script>
	window.active_timers = 0;	//acts like a semaphore for waiting the previous command to be fully typed into the shell

	"{%if expression_info.content%}"
		type("{{expression_info.content}}", "expression_slot", 1, false, false, false);
	"{% endif %}"
	addHomeEvents();
	"{% if request.user.is_authenticated %}"
		add_report_events();
	"{% endif %}"
</script>

<script>filters_button_style()</script>
{% endblock %}

vocapp/templates/vocapp/login.html
{% extends "layout_template.html" %}

{% block main %}
{% load static %}
<main class="flex_container_row_vcent">
	<div class="enter_container flex_container_col_cent">
		<h1>Login</h1>
		<form class="flex_container_col_hcent" method="POST">
			{% csrf_token %}
			<div class="form_field_login">
				<label for="id_username">Username:</label>
				{{ form.username }}
			</div>

			<div class="form_field_login">
				<label for="id_password">Password:</label>
				{{ form.password }}
			</div>

			<button type="submit" onclick="hideErrorMessage()" id="submit_login">Login</button>
		</form>
		{% if status == "ERROR" %}
			<p class="error_message">{{ response }}</p>
		{% endif %}
	</div>
</main>

<script src="{% static 'vocapp/js/typing_sim.js' %}"></script>
<script src="{% static 'vocapp/js/login.js' %}"></script>
<script>addLoginEvent()</script>
{% endblock %}

vocapp/templates/vocapp/signin.html
<!DOCTYPE html>
<html>
	<head>
		<title>Engvocab</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<!-- <link rel="shortcut icon" type="image/x-icon" href="style/favicon.ico"/> -->
	</head>
	<body>
		<nav>
			<ul>
				<li><a href="{%url 'vocapp:home'%}">Home</a></li>
				<li><a href="{%url 'vocapp:search'%}">Search</a></li>
				<li><a href="{%url 'vocapp:dashboard'%}">Dashboard</a></li>
			</ul>
		<main>
			<h1>Signup</h1>
			<form method="POST">
				{% csrf_token %}
				{{ form.as_p }}
				<button type="submit">Signup</button>
			</form>
			Already have an account? <a href="{%url 'vocapp:login'%}">Login</a>
		</main>
	</body>
</html>